
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: Jualon_development
  username: cybergarage
  password: 123456
  host: localhost

test:
  <<: *default
  database: Jualon_test
  username: cybergarage
  password: 123456
  host: localhost
production:
  <<: *default
  database: Jualon_production
  username: Jualon49203123Jualon
  host: localhost
  password: 123456