# JalaAdmin.create(email: 'access@jalaon.com', password: 'jalamedia')
# JalaAdmin.create(email: 'lintangarief13@gmail.com', password: 'yakuji13')
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
# AdminUser.create!(email: 'admin@jalaon.com', password: 'password', password_confirmation: 'password')
# ServiceField.create!([
#   {name: "Delivery", field_type: "check_box", required: false, service_category_id: 1},
#   {name: "TakeAways", field_type: "check_box", required: false, service_category_id: 1},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 1},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 1},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 1},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 1},
#   {name: "Type Kendaraan", field_type: "text_field", required: false, service_category_id: 2},
#   {name: "No Kendaraan", field_type: "text_field", required: false, service_category_id: 2},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 2},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 2},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 2},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 2},
#   {name: "Harga", field_type: "text_field", required: false, service_category_id: 3},
#   {name: "Type Rate", field_type: "text_field", required: false, service_category_id: 3},
#   {name: "House Service", field_type: "check_box", required: false, service_category_id: 3},
#   {name: "OutSide Service", field_type: "check_box", required: false, service_category_id: 3},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 3},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 3},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 3},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 3},
#   {name: "Harga", field_type: "text_field", required: false, service_category_id: 4},
#   {name: "Type Rate", field_type: "text_field", required: false, service_category_id: 4},
#   {name: "Delivery", field_type: "check_box", required: false, service_category_id: 4},
#   {name: "TakeAways", field_type: "check_box", required: false, service_category_id: 4},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 4},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 4},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 4},
#   {name: "Harga", field_type: "text_field", required: false, service_category_id: 5},
#   {name: "Type Rate", field_type: "text_field", required: false, service_category_id: 5},
#   {name: "House Service", field_type: "check_box", required: false, service_category_id: 5},
#   {name: "Outside Service", field_type: "check_box", required: false, service_category_id: 5},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 5},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 5},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 5},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 5},
#   {name: "Harga", field_type: "text_field", required: false, service_category_id: 6},
#   {name: "Type Rate", field_type: "text_field", required: false, service_category_id: 6},
#   {name: "House Service", field_type: "check_box", required: false, service_category_id: 6},
#   {name: "Outside Service", field_type: "check_box", required: false, service_category_id: 6},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 6},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 6},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 6},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 6},
#   {name: "Harga", field_type: "text_field", required: false, service_category_id: 7},
#   {name: "Type Rate", field_type: "text_field", required: false, service_category_id: 7},
#   {name: "Area Service", field_type: "text_field", required: false, service_category_id: 7},
#   {name: "Jam Kerja", field_type: "text_field", required: false, service_category_id: 7},
#   {name: "Available", field_type: "check_box", required: false, service_category_id: 7},
#   {name: "Other", field_type: "text_field", required: false, service_category_id: 7}
# ])
